# Generated by Django 3.1.7 on 2021-03-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0003_auto_20210321_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedbacks',
            name='feedback',
            field=models.BooleanField(blank=True, choices=[(None, ''), (True, 'Good'), (False, 'Bad')], null=True),
        ),
    ]
