# Generated by Django 3.1.7 on 2021-03-21 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offers',
            options={'ordering': ['created_at']},
        ),
    ]
