# Generated by Django 3.1.7 on 2021-03-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_auto_20210321_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='discount_type',
            field=models.BooleanField(choices=[(False, 'Flat'), (True, 'Percentage')], default=False),
        ),
    ]
